import fs from "node:fs";
import { launch, login, BASE } from "../menu-e2e/lib.mjs";
const OUT = process.env.SHOTS ?? "/tmp/claude-0/shots/blocks";
fs.mkdirSync(OUT, { recursive: true });
const b = await launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2, locale: "it-IT" });
const p = await ctx.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push(e.message));
p.on("console", (m) => m.type() === "error" && errs.push(m.text().slice(0, 150)));
await login(p, "andrea", process.env.E2E_ADMIN_PASSWORD);
await p.goto(`${BASE}/gestione-menu`, { waitUntil: "networkidle" });
await p.getByRole("button", { name: /Ricordamelo più tardi/i }).click().catch(() => {});
await p.screenshot({ path: `${OUT}/b01-gestione.png` });
await p.getByRole("button", { name: "+ Aggiungi" }).first().click();
await p.waitForTimeout(500);
await p.screenshot({ path: `${OUT}/b02-nuovo.png` });
await b.close();
console.log(errs.length ? errs.join(";") : "nessun errore");
