-- Regione (e paese, solo per i vini stranieri) dei vini della carta, come
-- concordato con il titolare. Riempie solo i campi ancora vuoti: quello che è
-- già stato scritto dalla gestione non viene toccato. Vini non elencati (o
-- rinominati nel frattempo) restano come sono e si completano dalla gestione.
-- Skyphos resta senza: da verificare.

UPDATE "MenuItem" SET "region" = $$Champagne$$ WHERE "name" = $$Champagne Henriot$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Francia$$ WHERE "name" = $$Champagne Henriot$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Champagne$$ WHERE "name" = $$Champagne de Villepin$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Francia$$ WHERE "name" = $$Champagne de Villepin$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Champagne$$ WHERE "name" = $$Champagne Pol Roger$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Francia$$ WHERE "name" = $$Champagne Pol Roger$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Trentino$$ WHERE "name" = $$Revì$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Teatrico$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Borgogna$$ WHERE "name" = $$Levert Frères$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Francia$$ WHERE "name" = $$Levert Frères$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Trentino$$ WHERE "name" = $$Rotari$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Lombardia$$ WHERE "name" = $$Conte Vistarino$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Lombardia$$ WHERE "name" = $$Colletto$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Távora-Varosa$$ WHERE "name" = $$Caves Raposeira$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Portogallo$$ WHERE "name" = $$Caves Raposeira$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Emilia-Romagna$$ WHERE "name" = $$Melegari$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Lombardia$$ WHERE "name" = $$Mattia Vezzola$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Marche$$ WHERE "name" = $$Collina delle Fate$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Emilia-Romagna$$ WHERE "name" = $$Angol d’Amig$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Basilicata$$ WHERE "name" = $$Arteteke$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Sicilia$$ WHERE "name" = $$Alberelli di Giodo$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Friuli-Venezia Giulia$$ WHERE "name" = $$Aquila del Torre$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Veneto$$ WHERE "name" = $$Villa della Torre$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Campania$$ WHERE "name" = $$Bellaria$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Poggio Cagnano$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Marche$$ WHERE "name" = $$La Distesa$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Calabria$$ WHERE "name" = $$‘A Vita$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Puglia$$ WHERE "name" = $$Domus Hortae$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Tenuta il Quinto$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Terre di Giotto$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Mastrojanni$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Grecia$$ WHERE "name" = $$Atma White$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Alsazia$$ WHERE "name" = $$François Weck$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Francia$$ WHERE "name" = $$François Weck$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Tenuta Argentiera$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Avignonesi$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Piemonte$$ WHERE "name" = $$Claudio Mariotto$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Lazio$$ WHERE "name" = $$Medevì$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Castello del Trebbio$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Friuli-Venezia Giulia$$ WHERE "name" = $$Borgo Canedo$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Le Macchiole$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Valle del Rodano$$ WHERE "name" = $$Famille Lançon$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Francia$$ WHERE "name" = $$Famille Lançon$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "country" = $$Francia$$ WHERE "name" = $$M. Chapoutier$$ AND "country" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Bulichella$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$One Belvedere$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Tenuta Fertuna$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Umbria$$ WHERE "name" = $$Decugnano dei Barbi$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Alto Adige$$ WHERE "name" = $$Schloss Englar$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
UPDATE "MenuItem" SET "region" = $$Toscana$$ WHERE "name" = $$Les Oiseaux d’Oulan Bator$$ AND "region" IS NULL AND "groupId" IN (SELECT g."id" FROM "MenuGroup" g JOIN "MenuSection" s ON s."id" = g."sectionId" WHERE s."kind" = 'WINE');
